In [1]:
import numpy as np

In [11]:
array1 = np.array([[10, 8], [3, 5]])
#運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?

#反矩陣
array1_inv = np.linalg.inv(array1)
print(array1_inv)

#乘上原矩陣
np.matmul(array1,array1_inv)

[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]


array([[1., 0.],
       [0., 1.]])

In [15]:
array1 = np.array([[10, 8], [3, 5]])
#運用上列array計算特徵值、特徵向量?

print('eigenvalue:', np.linalg.eig(array1)[0])
print('eigenvector:', np.linalg.eig(array1)[1])

eigenvalue: [13.  2.]
eigenvector: [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [17]:
array1 = np.array([[10, 8], [3, 5]])
#運用上列array計算SVD?

np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))