In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np
np.__version__

'1.19.2'

In [21]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
import numpy as np
a = np.linspace(0,20,num=21,endpoint=True,retstep=False, dtype=int, axis=0)
print(a)

b = np.arange(0,21)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [19]:
#2.呈上題，將以上數列取出偶數。

a[0::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
#3.呈1題，將數列取出3的倍數。

a[0::3]

array([ 0,  3,  6,  9, 12, 15, 18])