# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [25]:
import numpy as np
a = np.arange(4).reshape(2,2)

print(a)

print('list(a): ', list(a))  # list of arrays
print('tolist(): ', a.tolist()) #list of list of int
print(type(list(a)[0]))
print(type(a.tolist()[0]))

print('list(): ', "由上面可知，在List內依舊維持為矩陣型態")
print('tolist(): ', "由上面可知，可轉換多層，將整個陣列視為是一個List的List元素")

[[0 1]
 [2 3]]
list(a):  [array([0, 1]), array([2, 3])]
tolist():  [[0, 1], [2, 3]]
<class 'numpy.ndarray'>
<class 'list'>
list():  由上面可知，在List內依舊維持為矩陣型態
tolist():  由上面可知，可轉換多層，將整個陣列視為是一個List的List元素


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [27]:
a = np.random.randint(10, size=6) 
print(a)
print('ndim: ', a.ndim)
print('shape: ', a.shape)
print('size: ', a.size)
print('dtype: ', a.dtype)
print('itemsize: ', a.itemsize)
print('Lenght: ', len(a))
print('type: ', type(a))

[6 7 0 0 2 9]
ndim:  1
shape:  (6,)
size:  6
dtype:  int32
itemsize:  4
Lenght:  6
type:  <class 'numpy.ndarray'>


In [28]:
b = np.random.randint(10, size=(3,4)) 
print(b)
print('ndim: ', b.ndim)
print('shape: ', b.shape)
print('size: ', b.size)
print('dtype: ', b.dtype)
print('itemsize: ', b.itemsize)
print('Lenght: ', len(b))
print('type: ', type(b))

[[5 0 9 2]
 [4 3 2 7]
 [8 3 7 5]]
ndim:  2
shape:  (3, 4)
size:  12
dtype:  int32
itemsize:  4
Lenght:  3
type:  <class 'numpy.ndarray'>


In [29]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print('ndim: ', c.ndim)
print('shape: ', c.shape)
print('size: ', c.size)
print('dtype: ', c.dtype)
print('itemsize: ', c.itemsize)
print('Lenght: ', len(c))
print('type: ', type(c))

[[[2 8]
  [2 1]
  [0 3]]

 [[9 8]
  [7 2]
  [9 0]]]
ndim:  3
shape:  (2, 3, 2)
size:  12
dtype:  int32
itemsize:  4
Lenght:  2
type:  <class 'numpy.ndarray'>


In [ ]:
#ndarray.ndim： 陣列有多少維度、形狀
#ndarray.shape： 每個維度的大小
#ndarray.size： 陣列當中有幾個元素
#ndarray.dtype： 陣列中的資料型態
#ndarray.itemsize： 陣列中每個元素佔用的空間
#Length: 長度
#type: 物件所屬型態

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [39]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[1, 6, 6, 0, 1, 1]
[1, 6, 6, 0, 1, 1]


In [40]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[9, 9, 9, 2], [4, 9, 3, 6], [7, 8, 0, 5]]
[array([9, 9, 9, 2]), array([4, 9, 3, 6]), array([7, 8, 0, 5])]


In [41]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[3, 5], [8, 9], [8, 7]], [[6, 7], [8, 2], [1, 9]]]
[array([[3, 5],
       [8, 9],
       [8, 7]]), array([[6, 7],
       [8, 2],
       [1, 9]])]


In [43]:
def tolist(iterable):
    if iterable != np.ndarray:
        return iterable
    forlist = []
    for array in iterable:
        forlist.append(tolist(array))
    return list(forlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[1 6 6 0 1 1]
[[9 9 9 2]
 [4 9 3 6]
 [7 8 0 5]]
[[[3 5]
  [8 9]
  [8 7]]

 [[6 7]
  [8 2]
  [1 9]]]


<ipython-input-43-96ce7aeaa6f1>:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if iterable != np.ndarray:
